export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
// Registration
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
// Authentication
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
// Login
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
// myFilms
export const GET_MY_FILMS = "GET_MY_FILMS";
export const GET_MY_FILMS_ERROR = "GET_MY_FILMS_ERROR";
export const CREATE_MY_FILM = "CREATE_MY_FILM";
export const CREATE_MY_FILM_ERROR = "CREATE_MY_FILM_ERROR";
export const WATCH_FILM = "WATCH_FILM";
export const WATCH_FILM_ERROR = "WATCH_FILM_ERROR";
export const UNWATCH_FILM = "UNWATCH_FILM";
export const UNWATCH_FILM_ERROR = "UNWATCH_FILM_ERROR";
export const DELETE_MY_FILM = "DELETE_MY_FILM";
export const DELETE_MY_FILM_ERROR = "DELETE_MY_FILM_ERROR";
export const SEARCH_MY_FILMS = "SEARCH_MY_FILMS";
// Films
export const GET_FILMS = "GET_FILMS";
export const GET_FILMS_ERROR = "GET_FILMS_ERROR";
export const CREATE_FILM = "CREATE_FILM";
export const CREATE_FILM_ERROR = "CREATE_FILM_ERROR";
export const UPDATE_FILM = "UPDATE_FILM";
export const UPDATE_FILM_ERROR = "UPDATE_FILM_ERROR";
export const SELECT_FILM = "SELECT_FILM";
export const DESELECT_FILM = "DESELECT_FILM";
export const SEARCH_FILMS = "SEARCH_FILMS";
// Category
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_ERROR = "GET_CATEGORIES_ERROR";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const CREATE_CATEGORY_ERROR = "CREATE_CATEGORY_ERROR";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_CATEGORY_ERROR = "UPDATE_CATEGORY_ERROR";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_CATEGORY_ERROR = "DELETE_CATEGORY_ERROR";
// Redirection
export const REDIRECT = "REDIRECT";
